accumulate_grad_batches: 1
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 32
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- herb
- WRK
- ken
- l5kit_repo
- data
default_root_dir: null
deterministic: false
distributed_backend: null
early_stop_callback: false
fast_dev_run: false
gradient_clip_val: 0
hidden_layer_dim_list:
- 2
- 4
- 8
input_dim: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  EAMAAAAAAAA=
latent_dim: 16
learning_rate: 0.001
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_gpu_memory: null
log_save_interval: 100
logger: true
max_epochs: 1000
max_steps: null
min_epochs: 1
min_steps: null
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 16
overfit_batches: 0.0
overfit_pct: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 50
sync_batchnorm: false
terminate_on_nan: false
test_percent_check: null
track_grad_norm: -1
train_percent_check: null
truncated_bptt_steps: null
val_check_interval: 1.0
val_percent_check: null
weights_save_path: null
weights_summary: full
